# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/abonn/Desktop/Cours ESIREM/4eme_Annee/Archi_Reconfigurable/Projet_TP/Projet_TP.srcs/sources_1/ip/fifo_imag_9b_32K/fifo_imag_9b_32K.xci
# IP: The module: 'fifo_imag_9b_32K' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/abonn/Desktop/Cours ESIREM/4eme_Annee/Archi_Reconfigurable/Projet_TP/Projet_TP.gen/sources_1/ip/fifo_imag_9b_32K/fifo_imag_9b_32K.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_imag_9b_32K'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/abonn/Desktop/Cours ESIREM/4eme_Annee/Archi_Reconfigurable/Projet_TP/Projet_TP.gen/sources_1/ip/fifo_imag_9b_32K/fifo_imag_9b_32K_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_imag_9b_32K'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/abonn/Desktop/Cours ESIREM/4eme_Annee/Archi_Reconfigurable/Projet_TP/Projet_TP.gen/sources_1/ip/fifo_imag_9b_32K/fifo_imag_9b_32K_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_imag_9b_32K'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/abonn/Desktop/Cours ESIREM/4eme_Annee/Archi_Reconfigurable/Projet_TP/Projet_TP.srcs/sources_1/ip/fifo_imag_9b_32K/fifo_imag_9b_32K.xci
# IP: The module: 'fifo_imag_9b_32K' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/abonn/Desktop/Cours ESIREM/4eme_Annee/Archi_Reconfigurable/Projet_TP/Projet_TP.gen/sources_1/ip/fifo_imag_9b_32K/fifo_imag_9b_32K.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_imag_9b_32K'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/abonn/Desktop/Cours ESIREM/4eme_Annee/Archi_Reconfigurable/Projet_TP/Projet_TP.gen/sources_1/ip/fifo_imag_9b_32K/fifo_imag_9b_32K_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_imag_9b_32K'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/abonn/Desktop/Cours ESIREM/4eme_Annee/Archi_Reconfigurable/Projet_TP/Projet_TP.gen/sources_1/ip/fifo_imag_9b_32K/fifo_imag_9b_32K_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_imag_9b_32K'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
